title: "Deep Neural Mel-Subband Beamformer for In-Car Speech Separation"
description: Vinay Kothapally, Yong Xu, Meng Yu, Shi-Xiong Zhang, Dong Yu
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
markdown: kramdown